version: '3.7'
services:
  caddy:
    image: docker pull ghcr.io/josh-tucker/dispatch:release
    container_name: dispatch
    ports:
      - 5000:5000/tcp
    restart: unless-stopped
    volumes:
      - /opt/dispatch:/data