version: '3.7'
services:
  dispatch:
    image: ghcr.io/josh-tucker/dispatch:release
    container_name: dispatch
    ports:
      - 5000:5000/tcp
    restart: unless-stopped
    environment:
    - DATABASE_URL=sqlite:////data/rss_database.db
    volumes:
      - /opt/dispatch/db:/data
      - /opt/dispatch/assets:/static/img
